### ISSUE TITLE
Certain rendered cell contents disappear on initial load

### ISSUE THREAD

**Issue by miachenmtl** [zekedroid/react-lru#3]
I'm trying to get this to work in my project using Handsontable. After loading, not all the visible cells that should be populated by `renderReactCell` appear, although you can see them flash for a moment before disappearing. The simplest way I found to reproduce this behavior is by taking your Codepen example and making the first column instead of the second column use `reactRenderer`, like so:
```javascript
    this.columns = [{
      data: 'row',
      header: 'row',
      renderer: reactRenderer,
    }, {
      data: 'jsx',
      header: 'React',
      width: 200,
    }];
```
When I do this, the first three rows are empty, in addition to the bottom-most visible row.

**Comment by zekedroid** [comment]
Interesting...I'm taking a look now to see what's going on.

**Comment by zekedroid** [comment]
@miachenmtl this seems to be a bug (or rather limitation) of Handsontable. It seems that the Handsontable does some magic to calculate column widths when the user doesn't specify a value (whether on the column or the table at large). In your example (and in fact if you try to use the renderer on any cell without a width), Handsontable will render the cells and then immediately check for their width to readjust the CSS. Unfortunately, it does not detect width correctly while React is rendering elements, causing a race condition ultimately "removing" the contents of what it assumes are empty `td`s.

A simple solution for now is to ensure you give each column a width as that fixes the issue entirely. If this isn't doable in your case, keep an eye out as I will be diving into the Handsontable code to see if there is a way around this, maybe by modifying `react-lru` with a hack to stop this behavior.

Thanks for pointing it out!

**Comment by zekedroid** [comment]
More on this issue:

The problem continues to be due to auto column width logic, however, the real culprit is a weird feature HOT seems to be using to make this calculation where it calls the render method into a buffer which never gets rendered. Since this is called AFTER the real renderers, the memoized React containers are being moved from their real location to the buffer, hence "removing" them from the real table.

A simple solution (for now) is to ensure the React rendering is being done on the master table by adding the following to the top of any react renderer that has no column width set. It's not ideal, but in the cases where a set width is not easily calculated it may be the only solution.

```javascript
if (!td.closest('.ht_master.handsontable')) return td;
```

See https://codepen.io/anon/pen/JMReZY?editors=0010

**Comment by miachenmtl** [comment]
Cool, thanks for your suggestions!

**Comment by veeru1087** [comment]
> More on this issue:
> 
> The problem continues to be due to auto column width logic, however, the real culprit is a weird feature HOT seems to be using to make this calculation where it calls the render method into a buffer which never gets rendered. Since this is called AFTER the real renderers, the memoized React containers are being moved from their real location to the buffer, hence "removing" them from the real table.
> 
> A simple solution (for now) is to ensure the React rendering is being done on the master table by adding the following to the top of any react renderer that has no column width set. It's not ideal, but in the cases where a set width is not easily calculated it may be the only solution.
> 
> ```js
> if (!td.closest('.ht_master.handsontable')) return td;
> ```
> 
> See https://codepen.io/anon/pen/JMReZY?editors=0010

@zekedroid Thank you so much for your work on React-lru! I have been using this with Handsontable, and ran into this issue today. However the issue was with cells in the fixed bottom rows. So I had to modify your solution (If condition) to use **.ht_clone_bottom_left_corner** and **.ht_clone_bottom**. Hope this help others. Again, you are awesome!
